// <auto-generated />
using System;
using DigiLog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigiLog.Migrations
{
    [DbContext(typeof(LogDbContext))]
    [Migration("20231218101731_TestMigration")]
    partial class TestMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DigiLog.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Department")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("DigiLog.Models.Tag", b =>
                {
                    b.Property<int>("TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TagNumber")
                        .HasColumnType("longtext");

                    b.HasKey("TagID");

                    b.ToTable("Tags", (string)null);

                    b.HasData(
                        new
                        {
                            TagID = 1,
                            DateCreated = new DateTime(2023, 12, 18, 11, 17, 31, 249, DateTimeKind.Local).AddTicks(3801),
                            DateModified = new DateTime(2023, 12, 18, 11, 17, 31, 249, DateTimeKind.Local).AddTicks(3810),
                            Deleted = false,
                            TagNumber = "VIS-A60"
                        },
                        new
                        {
                            TagID = 2,
                            DateCreated = new DateTime(2023, 12, 18, 11, 17, 31, 249, DateTimeKind.Local).AddTicks(3811),
                            DateModified = new DateTime(2023, 12, 18, 11, 17, 31, 249, DateTimeKind.Local).AddTicks(3812),
                            Deleted = false,
                            TagNumber = "VIS-A61"
                        },
                        new
                        {
                            TagID = 3,
                            DateCreated = new DateTime(2023, 12, 18, 11, 17, 31, 249, DateTimeKind.Local).AddTicks(3813),
                            DateModified = new DateTime(2023, 12, 18, 11, 17, 31, 249, DateTimeKind.Local).AddTicks(3813),
                            Deleted = false,
                            TagNumber = "VIS-A62"
                        },
                        new
                        {
                            TagID = 4,
                            DateCreated = new DateTime(2023, 12, 18, 11, 17, 31, 249, DateTimeKind.Local).AddTicks(3815),
                            DateModified = new DateTime(2023, 12, 18, 11, 17, 31, 249, DateTimeKind.Local).AddTicks(3816),
                            Deleted = false,
                            TagNumber = "VIS-A78"
                        },
                        new
                        {
                            TagID = 5,
                            DateCreated = new DateTime(2023, 12, 18, 11, 17, 31, 249, DateTimeKind.Local).AddTicks(3817),
                            DateModified = new DateTime(2023, 12, 18, 11, 17, 31, 249, DateTimeKind.Local).AddTicks(3817),
                            Deleted = false,
                            TagNumber = "VIS-A66"
                        },
                        new
                        {
                            TagID = 6,
                            DateCreated = new DateTime(2023, 12, 18, 11, 17, 31, 249, DateTimeKind.Local).AddTicks(3818),
                            DateModified = new DateTime(2023, 12, 18, 11, 17, 31, 249, DateTimeKind.Local).AddTicks(3818),
                            Deleted = false,
                            TagNumber = "VIS-A56"
                        },
                        new
                        {
                            TagID = 7,
                            DateCreated = new DateTime(2023, 12, 18, 11, 17, 31, 249, DateTimeKind.Local).AddTicks(3819),
                            DateModified = new DateTime(2023, 12, 18, 11, 17, 31, 249, DateTimeKind.Local).AddTicks(3819),
                            Deleted = false,
                            TagNumber = "VIS-A87"
                        },
                        new
                        {
                            TagID = 8,
                            DateCreated = new DateTime(2023, 12, 18, 11, 17, 31, 249, DateTimeKind.Local).AddTicks(3820),
                            DateModified = new DateTime(2023, 12, 18, 11, 17, 31, 249, DateTimeKind.Local).AddTicks(3820),
                            Deleted = false,
                            TagNumber = "VIS-A78"
                        },
                        new
                        {
                            TagID = 9,
                            DateCreated = new DateTime(2023, 12, 18, 11, 17, 31, 249, DateTimeKind.Local).AddTicks(3821),
                            DateModified = new DateTime(2023, 12, 18, 11, 17, 31, 249, DateTimeKind.Local).AddTicks(3821),
                            Deleted = false,
                            TagNumber = "VIS-A88"
                        },
                        new
                        {
                            TagID = 10,
                            DateCreated = new DateTime(2023, 12, 18, 11, 17, 31, 249, DateTimeKind.Local).AddTicks(3822),
                            DateModified = new DateTime(2023, 12, 18, 11, 17, 31, 249, DateTimeKind.Local).AddTicks(3822),
                            Deleted = false,
                            TagNumber = "VIS-A48"
                        });
                });

            modelBuilder.Entity("DigiLog.Models.Visitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ContactAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Photo")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<int>("ReasonForVisit")
                        .HasColumnType("int");

                    b.Property<string>("ReasonForVisitDescription")
                        .HasColumnType("longtext");

                    b.Property<int>("TagID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Visitors");
                });

            modelBuilder.Entity("DigiLog.Models.Visitor", b =>
                {
                    b.HasOne("DigiLog.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
