// <auto-generated />
using System;
using DigiLog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigiLog.Migrations
{
    [DbContext(typeof(LogDbContext))]
    [Migration("20240110143418_LongMigration")]
    partial class LongMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DigiLog.Models.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Department")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("DigiLog.Models.Tag", b =>
                {
                    b.Property<long>("TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TagNumber")
                        .HasColumnType("longtext");

                    b.HasKey("TagID");

                    b.ToTable("Tags", (string)null);

                    b.HasData(
                        new
                        {
                            TagID = 1L,
                            DateCreated = new DateTime(2024, 1, 10, 15, 34, 18, 124, DateTimeKind.Local).AddTicks(5003),
                            DateModified = new DateTime(2024, 1, 10, 15, 34, 18, 124, DateTimeKind.Local).AddTicks(5012),
                            Deleted = false,
                            TagNumber = "VIS-A60"
                        },
                        new
                        {
                            TagID = 2L,
                            DateCreated = new DateTime(2024, 1, 10, 15, 34, 18, 124, DateTimeKind.Local).AddTicks(5013),
                            DateModified = new DateTime(2024, 1, 10, 15, 34, 18, 124, DateTimeKind.Local).AddTicks(5014),
                            Deleted = false,
                            TagNumber = "VIS-A61"
                        },
                        new
                        {
                            TagID = 3L,
                            DateCreated = new DateTime(2024, 1, 10, 15, 34, 18, 124, DateTimeKind.Local).AddTicks(5015),
                            DateModified = new DateTime(2024, 1, 10, 15, 34, 18, 124, DateTimeKind.Local).AddTicks(5016),
                            Deleted = false,
                            TagNumber = "VIS-A62"
                        },
                        new
                        {
                            TagID = 4L,
                            DateCreated = new DateTime(2024, 1, 10, 15, 34, 18, 124, DateTimeKind.Local).AddTicks(5016),
                            DateModified = new DateTime(2024, 1, 10, 15, 34, 18, 124, DateTimeKind.Local).AddTicks(5017),
                            Deleted = false,
                            TagNumber = "VIS-A78"
                        },
                        new
                        {
                            TagID = 5L,
                            DateCreated = new DateTime(2024, 1, 10, 15, 34, 18, 124, DateTimeKind.Local).AddTicks(5018),
                            DateModified = new DateTime(2024, 1, 10, 15, 34, 18, 124, DateTimeKind.Local).AddTicks(5018),
                            Deleted = false,
                            TagNumber = "VIS-A66"
                        },
                        new
                        {
                            TagID = 6L,
                            DateCreated = new DateTime(2024, 1, 10, 15, 34, 18, 124, DateTimeKind.Local).AddTicks(5019),
                            DateModified = new DateTime(2024, 1, 10, 15, 34, 18, 124, DateTimeKind.Local).AddTicks(5019),
                            Deleted = false,
                            TagNumber = "VIS-A56"
                        },
                        new
                        {
                            TagID = 7L,
                            DateCreated = new DateTime(2024, 1, 10, 15, 34, 18, 124, DateTimeKind.Local).AddTicks(5020),
                            DateModified = new DateTime(2024, 1, 10, 15, 34, 18, 124, DateTimeKind.Local).AddTicks(5021),
                            Deleted = false,
                            TagNumber = "VIS-A87"
                        },
                        new
                        {
                            TagID = 8L,
                            DateCreated = new DateTime(2024, 1, 10, 15, 34, 18, 124, DateTimeKind.Local).AddTicks(5022),
                            DateModified = new DateTime(2024, 1, 10, 15, 34, 18, 124, DateTimeKind.Local).AddTicks(5022),
                            Deleted = false,
                            TagNumber = "VIS-A78"
                        },
                        new
                        {
                            TagID = 9L,
                            DateCreated = new DateTime(2024, 1, 10, 15, 34, 18, 124, DateTimeKind.Local).AddTicks(5023),
                            DateModified = new DateTime(2024, 1, 10, 15, 34, 18, 124, DateTimeKind.Local).AddTicks(5023),
                            Deleted = false,
                            TagNumber = "VIS-A88"
                        },
                        new
                        {
                            TagID = 10L,
                            DateCreated = new DateTime(2024, 1, 10, 15, 34, 18, 124, DateTimeKind.Local).AddTicks(5024),
                            DateModified = new DateTime(2024, 1, 10, 15, 34, 18, 124, DateTimeKind.Local).AddTicks(5024),
                            Deleted = false,
                            TagNumber = "VIS-A48"
                        });
                });

            modelBuilder.Entity("DigiLog.Models.Visitor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ContactAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Photo")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<int>("ReasonForVisit")
                        .HasColumnType("int");

                    b.Property<string>("ReasonForVisitDescription")
                        .HasColumnType("longtext");

                    b.Property<long>("TagID")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Visitors");
                });

            modelBuilder.Entity("DigiLog.Models.Visitor", b =>
                {
                    b.HasOne("DigiLog.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
